[project]
name = "dbt-community"
version = "0.1.0"
description = "Snowflake DBT project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.10.15",
    "sqlfluff>=3.4.1",
    "sqlfluff-templater-dbt>=3.4.1",
    "dbt-snowflake>=1.10.0,<1.11.0",
    "shandy-sqlfmt[jinjafmt]"
]

[tool.sqlfmt]
line_length = 99
dialect = "snowflake"
check = false
fast = true
quiet = true
verbose = true

[tool.sqlfluff]
config_file = "deployment/scripts/.sqlfluff"
